Update script

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1,7 +1,29 @@
 format_version: 1.1.0
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
-
+app:
+  envs:
+  - BITRISE_STEP_ID: install-bundler
+  - BITRISE_STEP_VERSION: $BITRISE_GIT_TAG
+  - BITRISE_STEP_GIT_CLONE_URL: https://github.com/igorcferreira/bitrise-step-run-spm-test-with-coverage.git
+  - MY_STEPLIB_REPO_FORK_GIT_URL: $MY_STEPLIB_REPO_FORK_GIT_URL
+trigger_map:
+- pull_request_source_branch: '*'
+  pull_request_target_branch: main
+  workflow: audit-this-step
+- tag: '*'
+  workflow: share-this-step
 workflows:
+  _configure_git:
+    steps:
+    - script:
+        title: Config git user
+        run_if: .IsCI
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -ex
+            git config --global user.name "${SHARE_ACTION_USER_NAME}"
+            git config --global user.email "${SHARE_ACTION_USER_EMAIL}"
   test:
     steps:
     - change-workdir:
@@ -11,20 +33,56 @@ workflows:
           files with just './some-file' in the step's code, which would
           work for testing the step from this directory directly
           but would break if the step is included in another `bitrise.yml`.
-        run_if: true
+        run_if: 'true'
         inputs:
         - path: ./_tmp
         - is_create_path: true
-    - path::./:
+    - path::./git:
         title: Step Test
         description: ''
-        run_if: true
+        run_if: 'true'
         inputs:
         - gemfile_path: './Gemfile.lock'
+    - script:
+        title: Check bundler version
+        inputs:
+        - content: |
+            #!/usr/bin/env bash
+            set -e
+
+            CURRENT_BUNDLER_VERSION=$(bundle --version | grep -o -E -i -w "[0-9\.]{1,}" | xargs)
+            if [ "${CURRENT_BUNDLER_VERSION}" = "2.0.1" ]; then
+              echo "Valid version"
+              gem uninstall bundler -v 2.0.1
+            else
+              echo "Invalid version. Expected 2.0.1, got ${CURRENT_BUNDLER_VERSION}"
+            fi
+    - path::./git:
+        title: Step Test
+        description: ''
+        run_if: 'true'
+        inputs:
+        - gemfilelock_dir: './'
+    - script:
+        title: Check bundler version
+        inputs:
+        - content: |
+            #!/usr/bin/env bash
+            set -e
+
+            CURRENT_BUNDLER_VERSION=$(bundle --version | grep -o -E -i -w "[0-9\.]{1,}" | xargs)
+            if [ "${CURRENT_BUNDLER_VERSION}" = "2.0.1" ]; then
+              echo "Valid version"
+              gem uninstall bundler -v 2.0.1
+            else
+              echo "Invalid version. Expected 2.0.1, got ${CURRENT_BUNDLER_VERSION}"
+            fi
           
   # ----------------------------------------------------------------
   # --- workflows to Share this step into a Step Library
   audit-this-step:
+    before_run:
+    - test
     steps:
     - script:
         inputs:
@@ -36,10 +94,10 @@ workflows:
   share-this-step:
     envs:
       # if you want to share this step into a StepLib
-      - MY_STEPLIB_REPO_FORK_GIT_URL:
-      - STEP_ID_IN_STEPLIB:
-      - STEP_GIT_VERION_TAG_TO_SHARE:
-      - STEP_GIT_CLONE_URL:
+      - MY_STEPLIB_REPO_FORK_GIT_URL: $MY_STEPLIB_REPO_FORK_GIT_URL
+      - STEP_ID_IN_STEPLIB: $BITRISE_STEP_ID
+      - STEP_GIT_VERION_TAG_TO_SHARE: $BITRISE_STEP_VERSION
+      - STEP_GIT_CLONE_URL: $BITRISE_STEP_GIT_CLONE_URL
     description: |-
       If this is the first time you try to share a Step you should
       first call: $ bitrise share
@@ -63,6 +121,7 @@ workflows:
       the way described in the guide printed at the end of the process.
     before_run:
     - audit-this-step
+    - _configure_git
     steps:
     - script:
         inputs:
